name: 'Yarukoto'
version: 0.0.1
description: >

#author Tsuguya Touma <touma@ryukyu-i.co.jp>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  sass: any
  angular: '>=1.0.0 <2.0.0'
  web_components: any
  redstone: '>=0.5.19 <0.6.0'
  oauth2: '>=0.9.3 <0.10.0'
  crypto: any
  mongo_dart: any
  connection_pool: any
  shelf_static: any
dependency_overrides:
  hop: '>=0.27.0'
  dartmocks: any
  unittest: any
  code_transformers: '>=0.2.3+1 <0.3.0'
  html5lib: '>=0.12.0 <0.13.0'
  barback: '>=0.15.2+2 <0.16.0'
transformers:
  - sass:
      style: compressed
      copy-sources: false
  - angular
